### ISSUE TITLE
Problem with numpy

### ISSUE THREAD

**Issue by Vglib** [Apress/python-for-matlab-development#6]
Hi, i run the test.py to generate data.pkl and read it with matlab R2022b,python3.9 and numpy 1.26. Some problems arise for conversion of numpy to double:

Error using double
Conversion to double from py.numpy.ndarray is not possible.

Error in py2mat (line 110)
          x_mat = complex(double(x_py.real+0), double(x_py.imag+0));

Error in py2mat (line 154)
          x_mat{r,c} = py2mat(x_py{r,c});

Error in py2mat (line 68)
        new_var = py2mat(x_mat.(fields{i}));

Error in pytest_pkl (line 5)
mP = py2mat(P);         % pickle data converted to MATLAB native variable

I downgraded numpy to 1.19 and it is still happening.

**Comment by AlDanial** [comment]
Can you post `data.pkl` and the command you're issuing to load its contents then convert the matrix?  I'd like to try it.  If `data.pkl` is too large or contains proprietary data perhaps make a small version of it with random values.

**Comment by Vglib** [comment]
Hi, i generate data.pkl following the example with:

#!/usr/bin/env python3
import pickle
import numpy as np
cm = np.array([[2., 3],[0, 1]]) - np.eye(2)*1j
a_list = ['this', 'is', 'a', 'complex', 'matrix',cm]
a_dict = { 1 : 1, 2 : 'two', 'three' : 3}
an_int = 42
some_bytes = b'1ee50ffe2fb5104144142f001a8ca94ae56b90cf'
X = np.arange(12,dtype=np.float16).reshape(3,4)
P = {
    'a_list' : a_list,
    'a_dict' : a_dict,
    'an_int' : an_int,
    'some_bytes' : some_bytes,
    'X' : X,
    }
with open('data.pkl', 'wb') as fh:
        pickle.dump(P, fh, pickle.HIGHEST_PROTOCOL)

****Matlab****
pickle = py.importlib.import_module('pickle');
fh = py.open('data.pkl', 'rb');
P = pickle.load(fh);    % pickle file loaded to Python variable
fh.close();
mP = py2mat(P);         % pickle data converted to MATLAB native variable

***** data.pkl ****
©}(a_list](thisisacomplexmatrixnumpy.core.numeric_frombuffer(@@ð¿@ð?ð¿numpydtypec16R(K<NNNJÿÿÿÿJÿÿÿÿKtbKKCtRea_dict}(KKKtwothreeKuan_intK*
some_bytesC(1ee50ffe2fb5104144142f001a8ca94ae56b90cfXh
(<@BDEFGHHIIhf2R(KhNNNJÿÿÿÿJÿÿÿÿKtbKKhtRu.

**Comment by AlDanial** [comment]
Here's what I get in MATLAB 2022b:
<pre>
>> pickle = py.importlib.import_module('pickle');
>> fh = py.open('data.pkl', 'rb');
>> P = pickle.load(fh); % pickle file loaded to Python variable
>> fh.close();
>> P

P = 

  Python dict with no properties.

    {'a_list': ['this', 'is', 'a', 'complex', 'matrix', array([[2.-1.j, 3.+0.j],
           [0.+0.j, 1.-1.j]])], 'a_dict': {1: 1, 2: 'two', 'three': 3}, 'an_int': 42, 'some_bytes': b'1ee50ffe2fb5104144142f001a8ca94ae56b90cf', 'X': array([[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.]], dtype=float16)}

>> py2mat(P)

key_list =

  1x3 cell array

    {1x1 py.int}    {1x1 py.int}    {1x5 py.str}


ans = 

  struct with fields:

        a_list: {["this"]  ["is"]  ["a"]  ["complex"]  ["matrix"]  [2x2 double]}
        a_dict: [1x1 struct]
        an_int: 42
    some_bytes: [49 101 101 53 48 102 102 101 50 102 98 53 49 48 52 49 52 52 ... ]
             X: [3x4 single]
</pre>

Perhaps you have an older copy of `py2mat.m`?

**Comment by Vglib** [comment]
I think, it is the last version: https://github.com/Apress/python-for-matlab-development/blob/main/code/matlab_py/py2mat.m

**Comment by AlDanial** [comment]
What happens if you run these two commands?  First create a random complex 2x2 NumPy array
<pre>
>> x_py = py.numpy.random.rand(int64(2),int64(2)).astype(py.numpy.complex128)

x_py = 

  Python ndarray:

   0.5328 + 0.0000i   0.2434 + 0.0000i
   0.7331 + 0.0000i   0.1363 + 0.0000i

    Use details function to view the properties of the Python object.

    Use double function to convert to a MATLAB array.
</pre>

Then try to convert it to a MATLAB variable using the command that fails for you in `py2mat.m`:
<pre>
>> complex(double(x_py.real+0), double(x_py.imag+0))

ans =

   0.5328 + 0.0000i   0.2434 + 0.0000i
   0.7331 + 0.0000i   0.1363 + 0.0000i
</pre>

**Comment by Vglib** [comment]
Here, my output:

x_py = py.numpy.random.rand(int64(2),int64(2)).astype(py.numpy.complex128)
x_py = 

  Python ndarray with properties:

           T: [1×1 py.numpy.ndarray]
        base: [1×1 py.NoneType]
      ctypes: [1×1 py.numpy.core._internal._ctypes]
        data: [1×2 py.memoryview]
       dtype: [1×1 py.numpy.dtype]
       flags: [1×1 py.numpy.flagsobj]
        flat: [1×1 py.numpy.flatiter]
        imag: [1×1 py.numpy.ndarray]
    itemsize: [1×1 py.int]
      nbytes: [1×1 py.int]
        ndim: [1×1 py.int]
        real: [1×1 py.numpy.ndarray]
       shape: [1×2 py.tuple]
        size: [1×1 py.int]
     strides: [1×2 py.tuple]

    [[0.00931741+0.j 0.87330605+0.j]
     [0.61138238+0.j 0.88073855+0.j]]

>> complex(double(x_py.real+0), double(x_py.imag+0))
Error using double
Conversion to double from py.numpy.ndarray is not possible.

**Comment by AlDanial** [comment]
It looks to me to be a version compatibility issue.  I'm running Python 3.8 with NumPy 1.22.3 in a virtual environment similar to `matpy` described at the bottom of https://al.danial.org/posts/set_up_matlab_python_environment/. 
<pre>
>> pyenv

ans = 

  PythonEnvironment with properties:

          Version: "3.8"
       Executable: "/usr/local/anaconda3/2023.03/envs/matpy/bin/python"
          Library: "/usr/local/anaconda3/2023.03/envs/matpy/lib/libpython3.8.so"
             Home: "/usr/local/anaconda3/2023.03/envs/matpy"
           Status: Loaded
    ExecutionMode: InProcess
        ProcessID: "2484903"
      ProcessName: "MATLAB"

>> py.numpy.version
Unable to resolve the name 'py.numpy.version'.
 
>> py.numpy.version.full_version

ans = 

  Python str with no properties.

    1.22.3
</pre>
Are you able to change your environment to be closer to this?

**Comment by Vglib** [comment]
I tried to replicate that environment but it is not working, the same error arise. I even tried with numpy 1.22 and 1.19.

**Comment by AlDanial** [comment]
I'm at a loss then.  The only thing I can suggest is filing a support issue with MathWorks, tell them the second command fails for you:
```
>> x_py = py.numpy.random.rand(int64(2),int64(2)).astype(py.numpy.complex128)
>> complex(double(x_py.real+0), double(x_py.imag+0))
```

**Comment by Vglib** [comment]
Thanks for your help. These will be helpful for explaining the issue.
